using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Humatrix_HRMS.Migrations
{
    /// <inheritdoc />
    public partial class AddAttendanceCorrections : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AppliedToAttendanceAt",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "Date",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "IsAppliedToAttendance",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "ReviewComment",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.RenameColumn(
                name: "ReviewedBy",
                table: "AttendanceCorrectionRequests",
                newName: "ReviewedByEmployeeId");

            migrationBuilder.RenameColumn(
                name: "OriginalCheckOut",
                table: "AttendanceCorrectionRequests",
                newName: "ExistingCheckOut");

            migrationBuilder.RenameColumn(
                name: "OriginalCheckIn",
                table: "AttendanceCorrectionRequests",
                newName: "ExistingCheckIn");

            migrationBuilder.RenameColumn(
                name: "IsAutoGenerated",
                table: "AttendanceCorrectionRequests",
                newName: "IsApplied");

            migrationBuilder.RenameColumn(
                name: "AppliedAt",
                table: "AttendanceCorrectionRequests",
                newName: "WorkDate");

            migrationBuilder.RenameColumn(
                name: "CorrectionRequestId",
                table: "AttendanceCorrectionRequests",
                newName: "AttendanceCorrectionRequestId");

            migrationBuilder.AlterColumn<string>(
                name: "Status",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(20)",
                oldMaxLength: 20);

            migrationBuilder.AlterColumn<string>(
                name: "Reason",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "AttendanceCorrectionRequests",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<string>(
                name: "HRRemarks",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CreatedAt",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "HRRemarks",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.RenameColumn(
                name: "WorkDate",
                table: "AttendanceCorrectionRequests",
                newName: "AppliedAt");

            migrationBuilder.RenameColumn(
                name: "ReviewedByEmployeeId",
                table: "AttendanceCorrectionRequests",
                newName: "ReviewedBy");

            migrationBuilder.RenameColumn(
                name: "IsApplied",
                table: "AttendanceCorrectionRequests",
                newName: "IsAutoGenerated");

            migrationBuilder.RenameColumn(
                name: "ExistingCheckOut",
                table: "AttendanceCorrectionRequests",
                newName: "OriginalCheckOut");

            migrationBuilder.RenameColumn(
                name: "ExistingCheckIn",
                table: "AttendanceCorrectionRequests",
                newName: "OriginalCheckIn");

            migrationBuilder.RenameColumn(
                name: "AttendanceCorrectionRequestId",
                table: "AttendanceCorrectionRequests",
                newName: "CorrectionRequestId");

            migrationBuilder.AlterColumn<string>(
                name: "Status",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "Reason",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AddColumn<DateTime>(
                name: "AppliedToAttendanceAt",
                table: "AttendanceCorrectionRequests",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateOnly>(
                name: "Date",
                table: "AttendanceCorrectionRequests",
                type: "date",
                nullable: false,
                defaultValue: new DateOnly(1, 1, 1));

            migrationBuilder.AddColumn<bool>(
                name: "IsAppliedToAttendance",
                table: "AttendanceCorrectionRequests",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "ReviewComment",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true);
        }
    }
}
