using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Humatrix_HRMS.Migrations
{
    /// <inheritdoc />
    public partial class AttendanceCorrectionNewUpdates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "RejectionReason",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.AlterColumn<string>(
                name: "Status",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(20)",
                maxLength: 20,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<string>(
                name: "Reason",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AddColumn<DateTime>(
                name: "AppliedToAttendanceAt",
                table: "AttendanceCorrectionRequests",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAppliedToAttendance",
                table: "AttendanceCorrectionRequests",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "AttendanceCorrectionRequests",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<Guid>(
                name: "OrganizationId",
                table: "AttendanceCorrectionRequests",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<DateTime>(
                name: "OriginalCheckIn",
                table: "AttendanceCorrectionRequests",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "OriginalCheckOut",
                table: "AttendanceCorrectionRequests",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "RequestType",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ReviewComment",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "AttendanceAuditLogs",
                columns: table => new
                {
                    AuditId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    OrganizationId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    AttendanceId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ChangedByUserId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChangedByRole = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Action = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    OldValues = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NewValues = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Remarks = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    ChangedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AttendanceAuditLogs", x => x.AuditId);
                    table.ForeignKey(
                        name: "FK_AttendanceAuditLogs_Attendances_AttendanceId",
                        column: x => x.AttendanceId,
                        principalTable: "Attendances",
                        principalColumn: "AttendanceId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AttendanceAuditLogs_AttendanceId",
                table: "AttendanceAuditLogs",
                column: "AttendanceId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AttendanceAuditLogs");

            migrationBuilder.DropColumn(
                name: "AppliedToAttendanceAt",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "IsAppliedToAttendance",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "OrganizationId",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "OriginalCheckIn",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "OriginalCheckOut",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "RequestType",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.DropColumn(
                name: "ReviewComment",
                table: "AttendanceCorrectionRequests");

            migrationBuilder.AlterColumn<string>(
                name: "Status",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(20)",
                oldMaxLength: 20);

            migrationBuilder.AlterColumn<string>(
                name: "Reason",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AddColumn<string>(
                name: "RejectionReason",
                table: "AttendanceCorrectionRequests",
                type: "nvarchar(max)",
                nullable: true);
        }
    }
}
