using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Humatrix_HRMS.Models.Documents;

/// <summary>
/// Documents generated BY the organization FOR employees/HR
/// Examples: Offer Letters, Warning Letters, Experience Letters, etc.
/// </summary>
public class OrgGeneratedDocument
{
    [Key]
    public Guid DocumentId { get; set; } = Guid.NewGuid();

    [Required]
    public Guid OrganizationId { get; set; }

    [Required]
    public Guid EmployeeId { get; set; }  // Recipient
    
    public Guid? TemplateId { get; set; }  // ← CHANGE HERE

    // Add with other properties (around line 40-50)
    public bool IsViewed { get; set; }
    public DateTime? ViewedAt { get; set; }

    // Document metadata
    [Required, MaxLength(200)]
    public string DocumentNumber { get; set; } = default!; 

    [Required, MaxLength(500)]
    public string DocumentName { get; set; } = default!;

    [MaxLength(500)]
    public string? Description { get; set; }

    // File storage
    [Required, MaxLength(500)]
    public string FileName { get; set; } = default!;

    [Required, MaxLength(500)]
    public string OriginalFileName { get; set; } = default!; 

    [Required, MaxLength(1000)]
    public string FilePath { get; set; } = default!;

    public long FileSize { get; set; }

    [Required, MaxLength(200)]
    public string MimeType { get; set; } = "application/pdf";

    // Document content snapshot (for audit)
    public string? ContentSnapshot { get; set; }  // JSON of data used to generate

    // Status
    [Required, MaxLength(50)]
    public string Status { get; set; } = "Issued"; // Issued, Acknowledged, Revoked, Expired

    // Acknowledgment
    public DateTime? AcknowledgedAt { get; set; }
    public string? AcknowledgedByEmployeeId { get; set; }
    public string? AcknowledgmentRemarks { get; set; }

    // Generation tracking
    [Required, MaxLength(450)]
    public string GeneratedByUserId { get; set; } = default!;

    [Required, MaxLength(50)]
    public string GeneratedByRole { get; set; } = default!; // OrgAdmin, HR

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    // Versioning
    public Guid? PreviousDocumentId { get; set; }
    public int Version { get; set; } = 1;
    public bool IsLatestVersion { get; set; } = true;

    // Soft delete
    public bool IsDeleted { get; set; }
    public DateTime? DeletedAt { get; set; }
    public string? DeletedByUserId { get; set; }

    // Navigation properties
    [ForeignKey("OrganizationId")]
    public Organization? Organization { get; set; }

    [ForeignKey("EmployeeId")]
    public Employee? Employee { get; set; }

    [ForeignKey("TemplateId")]
    public OrgDocumentTemplate? Template { get; set; }

    [ForeignKey("PreviousDocumentId")]
    public OrgGeneratedDocument? PreviousDocument { get; set; }

    public ICollection<OrgDocumentHistory> History { get; set; } = new List<OrgDocumentHistory>();
}

/// <summary>
/// Audit history for organization generated documents
/// </summary>
public class OrgDocumentHistory
{
    [Key]
    public long HistoryId { get; set; }

    public Guid DocumentId { get; set; }
    public string Action { get; set; } = default!; // Generated, Acknowledged, Revoked, Deleted
    public string? OldValue { get; set; }
    public string? NewValue { get; set; }
    public string PerformedByUserId { get; set; } = default!;
    public string PerformedByRole { get; set; } = default!;
    public DateTime PerformedAt { get; set; } = DateTime.UtcNow;
    public string? Remarks { get; set; }

    [ForeignKey("DocumentId")]
    public OrgGeneratedDocument? Document { get; set; }
}