using Humatrix_HRMS.Models;
using Humatrix_HRMS.Models.Documents;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System.Text;
using System.Text.Json;
using static System.Collections.Specialized.BitVector32;

namespace Humatrix_HRMS.Services.AI;

public class AIDocumentService : IAIDocumentService
{
    private readonly IConfiguration _configuration;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<AIDocumentService> _logger;

    public AIDocumentService(
        IConfiguration configuration,
        IHttpClientFactory httpClientFactory,
        ILogger<AIDocumentService> logger)
    {
        _configuration = configuration;
        _httpClientFactory = httpClientFactory;
        _logger = logger;
    }

    public async Task<string> GenerateDocumentContentAsync(
        string templateName,
        string category,
        Employee employee,
        Dictionary<string, string>? customData,
        string generatedBy)
    {
        // Build the prompt for AI
        var prompt = BuildPrompt(templateName, category, employee, customData, generatedBy);

        // Call AI API (OpenAI/Azure OpenAI)
        var aiResponse = await CallAIApiAsync(prompt);

        // Extract and return the generated content
        return ExtractContentFromResponse(aiResponse);
    }

    public async Task<List<AIDocumentSuggestion>> SuggestDocumentsAsync(Employee employee)
    {
        var suggestions = new List<AIDocumentSuggestion>();

        // Calculate tenure in days
        var tenureDays = (DateTime.UtcNow - employee.JoiningDate).Days;

        // AI-powered suggestions based on employee data
        var prompt = $@"
        Analyze this employee and suggest document types that should be generated:
        - Name: {employee.FirstName} {employee.LastName}
        - Designation: {employee.Designation?.Name ?? "N/A"}
        - Department: {employee.Department?.Name ?? "N/A"}
        - Joining Date: {employee.JoiningDate:dd MMM yyyy}
        - Tenure: {tenureDays} days
        - Status: {employee.Status}

        Return JSON array of suggestions with: documentType, reason, priority (1-10)
        ";

        var aiResponse = await CallAIApiAsync(prompt);
        suggestions = ParseSuggestionsFromResponse(aiResponse);

        // Add rule-based suggestions as fallback
        AddRuleBasedSuggestions(employee, suggestions);

        return suggestions;
    }

    public async Task<string> GenerateNotificationMessageAsync(
     string documentName,
     Employee employee,
     string documentNumber)
    {
        var prompt = $@"
Generate a VERY SHORT (max 50 words), professional notification message for an employee.

Document: {documentName}
Employee: {employee.FirstName}
Document Number: {documentNumber}

Requirements:
- Plain text ONLY (NO HTML, NO markdown, NO special characters)
- 1-2 sentences maximum
- Warm but professional tone
- Include call to action to view document

Example: Dear {employee.FirstName}, your {documentName} is ready. Please review it in the Documents section.
";

        var response = await CallAIApiAsync(prompt);

        // Strip all HTML and special characters
        var cleanResponse = System.Text.RegularExpressions.Regex.Replace(response, @"<[^>]*>", "");
        cleanResponse = cleanResponse.Replace("```", "").Replace("\n", " ").Trim();

        // Limit to 200 characters
        if (cleanResponse.Length > 200)
            cleanResponse = cleanResponse.Substring(0, 197) + "...";

        return string.IsNullOrEmpty(cleanResponse) ? $"Your {documentName} is ready. View in Documents." : cleanResponse;
    }

    // ==================== PRIVATE METHODS ====================

    private string BuildPrompt(
        string templateName,
        string category,
        Employee employee,
        Dictionary<string, string>? customData,
        string generatedBy)
    {
        var employeeInfo = $@"
        EMPLOYEE INFORMATION:
        - Full Name: {employee.FirstName} {employee.LastName}
        - Designation: {employee.Designation?.Name ?? "N/A"}
        - Department: {employee.Department?.Name ?? "N/A"}
        - Employee Code: {employee.EmployeeCode ?? "N/A"}
        - Joining Date: {employee.JoiningDate:dd MMM yyyy}
        - Gender: {employee.Gender ?? "N/A"}
        ";

        var customDataInfo = customData != null && customData.Any()
            ? $"ADDITIONAL DATA: {JsonSerializer.Serialize(customData)}"
            : "";

        return $@"
        You are an HR document generator. Create a professional {templateName} ({category}) for the following employee.

        {employeeInfo}
        {customDataInfo}

        Generated by: {generatedBy}
        Current Date: {DateTime.UtcNow:dd MMM yyyy}

        RULES:
        1. Use professional, warm, and respectful tone
        2. Include all relevant employee details naturally in the content
        3. For Offer Letter: Include joining date, designation, department, probation period
        4. For Warning Letter: Be firm but fair, include issue details and expected actions
        5. For Appreciation Letter: Be encouraging and specific about achievements
        6. For Experience Letter: Highlight tenure, role, and positive attributes
        7. Format as HTML with proper headings and paragraphs
        8. DO NOT include any explanations, just return the HTML content

        Generate the complete document content:
        ";
    }

    private async Task<string> CallAIApiAsync(string prompt)
    {
        var apiKey = _configuration["OpenAI:ApiKey"];
        var baseUrl = _configuration["OpenAI:BaseUrl"] ?? "https://api.groq.com/openai/v1";
        var model = _configuration["OpenAI:Model"] ?? "llama-3.3-70b-versatile";

        if (string.IsNullOrEmpty(apiKey))
        {
            return GenerateFallbackContent(prompt);
        }

        // Groq uses OpenAI-compatible format
        using var client = _httpClientFactory.CreateClient();
        client.DefaultRequestHeaders.Add("Authorization", $"Bearer {apiKey}");

        var requestBody = new
        {
            model = model,
            messages = new[]
            {
            new { role = "system", content = "You are an HR document generation assistant. Return ONLY HTML content, no explanations." },
            new { role = "user", content = prompt }
        },
            temperature = 0.7,
            max_tokens = 2000
        };

        var response = await client.PostAsync(
            $"{baseUrl}/chat/completions",
            new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json"));

        var jsonResponse = await response.Content.ReadAsStringAsync();

        if (!response.IsSuccessStatusCode)
        {
            _logger.LogWarning($"Groq API error: {jsonResponse}");
            return GenerateFallbackContent(prompt);
        }

        using var doc = JsonDocument.Parse(jsonResponse);
        var content = doc.RootElement
            .GetProperty("choices")[0]
            .GetProperty("message")
            .GetProperty("content")
            .GetString();

        return content ?? GenerateFallbackContent(prompt);
    }

    private string GenerateMockAIResponse(string prompt)
    {
        // Return a beautiful, professional HTML document
        return @"
<div style='font-family: ''Georgia'', serif; max-width: 800px; margin: 0 auto; padding: 40px; background: white;'>
    <div style='text-align: center; border-bottom: 2px solid #4a6741; margin-bottom: 30px; padding-bottom: 20px;'>
        <h1 style='color: #2c3e50; margin: 0;'>Offer of Employment</h1>
    </div>
    
    <p>Dear {{FirstName}},</p>
    
    <p>We are absolutely delighted to extend this offer of employment for the position of <strong>{{Designation}}</strong> in the <strong>{{Department}}</strong> department at {{OrganizationName}}.</p>
    
    <div style='background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;'>
        <h3 style='color: #2c3e50; margin-top: 0;'>📋 Offer Details</h3>
        <ul style='list-style: none; padding-left: 0;'>
            <li><strong>✨ Position:</strong> {{Designation}}</li>
            <li><strong>🏢 Department:</strong> {{Department}}</li>
            <li><strong>📅 Joining Date:</strong> {{JoiningDate}}</li>
            <li><strong>👤 Reporting To:</strong> Department Head</li>
            <li><strong>📝 Probation Period:</strong> 6 months</li>
        </ul>
    </div>
    
    <p>We were thoroughly impressed by your skills, experience, and enthusiasm during the interview process. We believe you will be a valuable asset to our team.</p>
    
    <div style='margin: 30px 0;'>
        <h3>📝 Next Steps</h3>
        <ol>
            <li>Review this offer letter carefully</li>
            <li>Complete the joining formalities</li>
            <li>Submit any requested documents</li>
        </ol>
    </div>
    
    <p>We look forward to welcoming you to the {{OrganizationName}} family and wish you a successful career ahead!</p>
    
    <div style='margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;'>
        <p>Warm Regards,<br/>
        <strong>{{GeneratedBy}}</strong><br/>
        {{OrganizationName}}</p>
    </div>
    
    <div style='text-align: center; margin-top: 50px; font-size: 12px; color: #888;'>
        <p>This is a system-generated document. Please contact HR for any queries.</p>
    </div>
</div>";
    }

    private string GenerateFallbackContent(string prompt)
    {
        return @"<h2>Document</h2><p>Document content will be generated.</p>";
    }

    private string ExtractContentFromResponse(string response)
    {
        // Clean up AI response - remove any markdown code blocks
        var cleaned = response.Replace("```html", "").Replace("```", "").Trim();
        return cleaned;
    }

    private List<AIDocumentSuggestion> ParseSuggestionsFromResponse(string response)
    {
        try
        {
            var suggestions = JsonSerializer.Deserialize<List<AIDocumentSuggestion>>(response);
            return suggestions ?? new List<AIDocumentSuggestion>();
        }
        catch
        {
            return new List<AIDocumentSuggestion>();
        }
    }

    private void AddRuleBasedSuggestions(Employee employee, List<AIDocumentSuggestion> suggestions)
    {
        var tenureDays = (DateTime.UtcNow - employee.JoiningDate).Days;

        // Rule: If employee joined within last 7 days, suggest Offer Letter
        if (tenureDays <= 7 && !suggestions.Any(s => s.DocumentType == "Offer Letter"))
        {
            suggestions.Add(new AIDocumentSuggestion
            {
                DocumentType = "Offer Letter",
                Reason = "Employee joined recently - Offer Letter pending",
                Priority = 10,
                SuggestedData = new Dictionary<string, string>
                {
                    { "JoiningDate", employee.JoiningDate.ToString("dd MMM yyyy") },
                    { "Designation", employee.Designation?.Name ?? "" },
                    { "Department", employee.Department?.Name ?? "" }
                }
            });
        }

        // Rule: After 6 months, suggest Confirmation Letter
        if (tenureDays >= 180 && tenureDays <= 190)
        {
            suggestions.Add(new AIDocumentSuggestion
            {
                DocumentType = "Confirmation Letter",
                Reason = "Probation period completed - Confirmation Letter needed",
                Priority = 8,
                SuggestedData = new Dictionary<string, string>
                {
                    { "ConfirmationDate", DateTime.UtcNow.AddDays(7).ToString("dd MMM yyyy") }
                }
            });
        }

        // Rule: If employee's last working day is set, suggest Experience Letter
        if (employee.LastWorkingDay.HasValue && employee.LastWorkingDay.Value <= DateTime.UtcNow.AddDays(15))
        {
            suggestions.Add(new AIDocumentSuggestion
            {
                DocumentType = "Experience Letter",
                Reason = "Employee is exiting - Experience Letter needed",
                Priority = 9,
                SuggestedData = new Dictionary<string, string>
                {
                    { "LastWorkingDay", employee.LastWorkingDay.Value.ToString("dd MMM yyyy") }
                }
            });
        }
    }

    // OpenAI Response Models
    private class OpenAIResponse
    {
        public List<Choice> choices { get; set; } = new();
    }

    private class Choice
    {
        public Message message { get; set; } = new();
    }

    private class Message
    {
        public string content { get; set; } = string.Empty;
    }
}